--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Endermanbugzjfc/Quest
build-by-default: false
branches:
- master
projects:
  Quest:
    path: ""
    libs:
    - src: SOF3/await-generator/await-generator
      version: ^3.4.3
    - src: SOF3/await-std/await-std
      version: ^0.2.0
    - src: poggit/libasynql/libasynql
      version: ^4.0.1
    - src: Paroxity/Commando/Commando # Poggit has stopped to build for CortexPE.
      version: ^3.0.0
    - src: DaisukeDaisukeTeam/libNpcDialogue/libNpcDialogue # refteams has never enabled Poggit.
      version: ^1.0.0
...

